---
driver:
  # vagrant
  name: vagrant
  customize:
    memory: 1024

driver_config:
  require_chef_omnibus: true

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04

suites:
  - name: server
    run_list:
      - role[sensu-server]
    attributes:
    driver:
      network:
      - ["private_network", {ip: "192.168.33.11"}]  # vagrant network

  - name: client
    run_list:
      - role[sensu-client]
    attributes:
    driver:
      network:
      - ["private_network", {ip: "192.168.33.101"}]  # vagrant network
